apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-deployment
  labels:
    app: user-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: user-auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/patient_journal_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: APP_JWT_SECRET
              value: "sEnMycketLangOchSakerHemligNyckelForHS512SomArMinst64TeckenLangForAttUndvikaDettaFel-DuKanHittaPaEnEgenOcksa"