apiVersion: v1
kind: Service
metadata:
  name: user-auth-service
  labels:
    app: user-auth
spec:
  type: LoadBalancer
  selector:
    app: user-auth
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082