apiVersion: v1
kind: Service
metadata:
  name: patient-journal-service
  labels:
    app: patient-journal
spec:
  type: LoadBalancer
  selector:
    app: patient-journal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080